name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün gece yarısında çalışacak şekilde ayarlanmıştır. İstersen cron zamanlamasını değiştirebilirsin.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Snake animasyonunu output branch'e pushlayacak
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
